const INCREMENT_COUNTER = "INCREMENT_COUNTER";
const DECREMENT_COUNTER = "DECREMENT_COUNTER";
const RESET_COUNTER = "RESET_COUNTER";
const SET_COUNTER = "SET_COUNTER";

export { INCREMENT_COUNTER, DECREMENT_COUNTER, RESET_COUNTER, SET_COUNTER };
